#!/usr/bin/env python3
# -*- coding: utf-8 -*-

def create_russian_animal_translations():
    """Create proper Russian translations for animals"""
    
    # Animal translations dictionary
    translations = {
        "aardvark": "ТРУБКОЗУБ",
        "african_lion": "АФРИКАНСКИЙ ЛЕВ", 
        "african_wild_dog": "АФРИКАНСКАЯ ДИКАЯ СОБАКА",
        "albatross": "АЛЬБАТРОС",
        "alligator": "АЛЛИГАТОР",
        "alpaca": "АЛЬПАКА",
        "anteater": "МУРАВЬЕД",
        "antelope": "АНТИЛОПА",
        "asiatic_lion": "АЗИАТСКИЙ ЛЕВ",
        "avocet": "ШИЛОКЛЮВКА",
        "axolotl": "АКСОЛОТЛЬ",
        "badger": "БАРСУК",
        "bald_eagle": "БЕЛОГОЛОВЫЙ ОРЛАН",
        "barbary_lion": "БЕРБЕРИЙСКИЙ ЛЕВ",
        "barracuda": "БАРРАКУДА",
        "basilisk": "ВАСИЛИСК",
        "bass": "ОКУНЬ",
        "bat": "ЛЕТУЧАЯ МЫШЬ",
        "bat_eared_fox": "БОЛЬШЕУХАЯ ЛИСИЦА",
        "bear": "МЕДВЕДЬ",
        "bison": "БИЗОН",
        "black_bear": "ЧЁРНЫЙ МЕДВЕДЬ",
        "bleak": "УКЛЕЙКА",
        "blue_jay": "ГОЛУБАЯ СОЙКА",
        "bluefin_tuna": "ГОЛУБОЙ ТУНЕЦ",
        "boa_constrictor": "УДАВ",
        "bobcat": "РЫСЬ",
        "bull_shark": "ТУПОРЫЛАЯ АКУЛА",
        "butterfly": "БАБОЧКА",
        "buzzard": "КАНЮК",
        "camel": "ВЕРБЛЮД",
        "caribou": "КАРИБУ",
        "cassowary": "КАЗУАР",
        "cat": "КОТ",
        "cheetah": "ГЕПАРД",
        "chicken": "КУРИЦА",
        "chimpanzee": "ШИМПАНЗЕ",
        "chipmunk": "БУРУНДУК",
        "clownfish": "РЫБА-КЛОУН",
        "coati": "КОАТИ",
        "cockatoo": "КАКАДУ",
        "condor": "КОНДОР",
        "cormorant": "БАКЛАН",
        "cougar": "ПУМА",
        "cow": "КОРОВА",
        "coyote": "КОЙОТ",
        "crab_eating_mongoose": "КРАБОЕД",
        "crab_eating_raccoon": "ЕНОТ-РАКОЕД",
        "crocodile": "КРОКОДИЛ",
        "crow": "ВОРОНА",
        "crucian_carp": "КАРАСЬ",
        "curlew": "КРОНШНЕП",
        "dace": "ЕЛЕЦ",
        "dachshund": "ТАКСА",
        "deer": "ОЛЕНЬ",
        "dingo": "ДИНГО",
        "dinosaur": "ДИНОЗАВР",
        "dog": "СОБАКА",
        "dolphin": "ДЕЛЬФИН",
        "donkey": "ОСЁЛ",
        "dotterel": "ХРУСТАН",
        "echidna": "ЕХИДНА",
        "eel": "УГОРЬ",
        "eland": "КАННА",
        "electric_eel": "ЭЛЕКТРИЧЕСКИЙ УГОРЬ",
        "elephant": "СЛОН",
        "elephant_seal": "МОРСКОЙ СЛОН",
        "elk": "ЛОСЬ",
        "emu": "ЭМУ",
        "ethiopian_wolf": "ЭФИОПСКИЙ ВОЛК",
        "european_mink": "ЕВРОПЕЙСКАЯ НОРКА",
        "falcon": "СОКОЛ",
        "ferret": "ХОРЁК",
        "finch": "ЗЯБЛИК",
        "fly": "МУХА",
        "fox": "ЛИСИЦА",
        "gazelle": "ГАЗЕЛЬ",
        "gecko": "ГЕККОН",
        "gerbil": "ПЕСЧАНКА",
        "gharial": "ГАВИАЛ",
        "giant_panda": "БОЛЬШАЯ ПАНДА",
        "giraffe": "ЖИРАФ",
        "gnu": "АНТИЛОПА ГНУ",
        "goldfinch": "ЩЕГОЛ",
        "goldfish": "ЗОЛОТАЯ РЫБКА",
        "goose": "ГУСЬ",
        "gorilla": "ГОРИЛЛА",
        "great_white_shark": "БОЛЬШАЯ БЕЛАЯ АКУЛА",
        "greenland_shark": "ГРЕНЛАНДСКАЯ АКУЛА",
        "guanaco": "ГУАНАКО",
        "guppy": "ГУППИ",
        "hammerhead_shark": "АКУЛА-МОЛОТ",
        "hamster": "ХОМЯК",
        "hartebeest": "КОНГОНИ",
        "hawk": "ЯСТРЕБ",
        "hedgehog": "ЁЖ",
        "hippo": "БЕГЕМОТ",
        "hornbill": "ПТИЦА-НОСОРОГ",
        "hummingbird": "КОЛИБРИ",
        "hyena": "ГИЕНА",
        "ide": "ЯЗЬ",
        "iguana": "ИГУАНА",
        "impala": "ИМПАЛА",
        "indri": "ИНДРИ",
        "insect": "НАСЕКОМОЕ",
        "jackal": "ШАКАЛ",
        "jaguar": "ЯГУАР",
        "jay": "СОЙКА",
        "jellyfish": "МЕДУЗА",
        "jungle_cat": "КАМЫШОВЫЙ КОТ",
        "kangaroo": "КЕНГУРУ",
        "koala": "КОАЛА",
        "komodo_dragon": "КОМОДСКИЙ ВАРАН",
        "kookaburra": "КУКАБАРРА",
        "kudu": "КУДУ",
        "labradoodle": "ЛАБРАДУДЛЬ",
        "lapwing": "ЧИБИС",
        "lemming": "ЛЕММИНГ",
        "lemur": "ЛЕМУР",
        "leopard": "ЛЕОПАРД",
        "leopard_gecko": "ЛЕОПАРДОВЫЙ ГЕККОН",
        "lion": "ЛЕВ",
        "lionfish": "КРЫЛАТКА",
        "lizard": "ЯЩЕРИЦА",
        "llama": "ЛАМА",
        "loon": "ГАГАРА",
        "loris": "ЛОРИ",
        "lynx": "РЫСЬ",
        "lyrebird": "ЛИРОХВОСТ",
        "macaw": "АРА",
        "magpie": "СОРОКА",
        "mallard": "КРЯКВА",
        "manatee": "ЛАМАНТИН",
        "mandrill": "МАНДРИЛ",
        "marsh_mongoose": "БОЛОТНЫЙ МАНГУСТ",
        "marten": "КУНИЦА",
        "mastiff": "МАСТИФ",
        "meerkat": "СУРИКАТ",
        "mink": "НОРКА",
        "mole": "КРОТ",
        "mongoose": "МАНГУСТ",
        "mongrel": "ДВОРНЯГА",
        "monkey": "ОБЕЗЬЯНА",
        "moorhen": "КАМЫШНИЦА",
        "moose": "ЛОСЬ",
        "moth": "МОЛЬ",
        "mudskipper": "ИЛИСТЫЙ ПРЫГУН",
        "mule": "МУЛ",
        "newt": "ТРИТОН",
        "nightingale": "СОЛОВЕЙ",
        "nutria": "НУТРИЯ",
        "ocelot": "ОЦЕЛОТ",
        "okapi": "ОКАПИ",
        "opossum": "ОПОССУМ",
        "orangutan": "ОРАНГУТАН",
        "oryx": "ОРИКС",
        "otter": "ВЫДРА",
        "owl": "СОВА",
        "ox": "БЫК",
        "panda": "ПАНДА",
        "panther": "ПАНТЕРА",
        "parakeet": "ПОПУГАЙЧИК",
        "parrot": "ПОПУГАЙ",
        "partridge": "КУРОПАТКА",
        "peacock": "ПАВЛИН",
        "peafowl": "ПАВЛИН",
        "pelican": "ПЕЛИКАН",
        "penguin": "ПИНГВИН",
        "persian_cat": "ПЕРСИДСКАЯ КОШКА",
        "pigeon": "ГОЛУБЬ",
        "pika": "ПИЩУХА",
        "pike": "ЩУКА",
        "pine_marten": "ЛЕСНАЯ КУНИЦА",
        "pink_salmon": "ГОРБУША",
        "pinniped": "ЛАСТОНОГИЕ",
        "platypus": "УТКОНОС",
        "polecat": "ХОРЁК",
        "pony": "ПОНИ",
        "porgy": "КАРАСЬ",
        "porpoise": "МОРСКАЯ СВИНЬЯ",
        "possum": "ПОССУМ",
        "prairie_dog": "ЛУГОВАЯ СОБАЧКА",
        "puffin": "ТУПИК",
        "puma": "ПУМА",
        "quail": "ПЕРЕПЕЛ",
        "quetzal": "КЕТЦАЛЬ",
        "quoll": "КУОЛЛ",
        "rabbit": "КРОЛИК",
        "raccoon": "ЕНОТ",
        "raccoon_dog": "ЕНОТОВИДНАЯ СОБАКА",
        "rat": "КРЫСА",
        "rattlesnake": "ГРЕМУЧАЯ ЗМЕЯ",
        "raven": "ВОРОН",
        "red_fox": "РЫЖАЯ ЛИСИЦА",
        "red_panda": "КРАСНАЯ ПАНДА",
        "red_wolf": "РЫЖИЙ ВОЛК",
        "reindeer": "СЕВЕРНЫЙ ОЛЕНЬ",
        "rhino": "НОСОРОГ",
        "rhinoceros": "НОСОРОГ",
        "roadrunner": "ДОРОЖНЫЙ БЕГУНОК"
    }
    
    return translations

def fix_russian_animals():
    """Fix Russian animal translations in the animal_world.txt file"""
    
    print("🇷🇺 ИСПРАВЛЕНИЕ РУССКИХ ПЕРЕВОДОВ ЖИВОТНЫХ")
    print("=" * 50)
    
    # Read English file to get the animal names
    with open('data/words/en/animal_world.txt', 'r', encoding='utf-8') as f:
        en_lines = f.readlines()
    
    # Get Russian translations
    translations = create_russian_animal_translations()
    
    # Process Russian file
    with open('data/words/ru/animal_world.txt', 'w', encoding='utf-8') as f:
        for i, line in enumerate(en_lines, 1):
            parts = line.strip().split(' - ')
            if len(parts) >= 3:
                number = parts[0]
                english_name = parts[1].lower()
                image_file = parts[2]
                
                # Get Russian translation
                russian_name = translations.get(english_name, english_name.upper().replace('_', ' '))
                
                f.write(f"{number} - {russian_name} - {image_file}\n")
    
    print(f"✅ Исправлен русский файл с {len(en_lines)} животными")

if __name__ == "__main__":
    fix_russian_animals() 